### ISSUE TITLE
multi-dimensional noise term in the objective function

### ISSUE THREAD

**Issue by marykh162** [odow/SDDP.jl#308] opened 2020-03-12 00:40 UTC
I am tying to add a multi-dimensional noise terms to the objective function. I am using the method explained in the documentation of the SDDP.jl (https://odow.github.io/SDDP.jl/latest/guides/add_multidimensional_noise_Terms/). 
I am getting the following error:
```julia
ERROR: LoadError: syntax: assignment not allowed inside tuple
```
I get the same error even when I try to run the following example code in the manual:
```Julia
julia> model = SDDP.LinearPolicyGraph(
               stages=3, lower_bound = 0, optimizer = GLPK.Optimizer
               ) do subproblem, t
           @variable(subproblem, x, SDDP.State, initial_value = 0.0)
           support = [(value = v, coefficient = c) for v in [1, 2] for c in [3, 4, 5]]
           probability = [pv * pc for pv in [0.5, 0.5] for pc in [0.3, 0.5, 0.2]]
           SDDP.parameterize(subproblem, support, probability) do ω
               JuMP.fix(x.out, ω.value)
               @stageobjective(subproblem, ω.coefficient * x.out)
               println("ω is: ", ω)
           end
       end;

julia> SDDP.simulate(model, 1);
```

I appreciate any help.

**Comment by odow** [comment] 2020-03-12 15:00
Are you using Julia 1.0 or greater?

What happens if you run
```Julia
julia> x = (a = 1, b = 2)
(a = 1, b = 2)
```

**Comment by marykh162** [comment] 2020-03-12 18:23
> 
> 
> Are you using Julia 1.0 or greater?
> 
> What happens if you run
> 
> ```julia
> julia> x = (a = 1, b = 2)
> (a = 1, b = 2)
> ```

Thanks for your response!
I am getting the same error when running julia> x = (a = 1, b = 2). My Julia version is 0.6.4.

**Comment by odow** [comment] 2020-03-12 19:00
You need to install Julia 1.0.

**Comment by marykh162** [comment] 2020-03-12 22:54
> You need to install Julia 1.0.

Thanks for your reply.
I installed Julia 1.0.5. Now, I am getting the following error while adding the SDDP package:
ERROR: Unsatisfiable requirements detected for package JuMP [4076af6c]:
 JuMP [4076af6c] log:
 ├─possible versions are: [0.18.3-0.18.6, 0.19.0-0.19.2, 0.20.0-0.20.1] or uninstalled
 └─restricted to versions 0.21.0-0.21 by SDDP [f4570300] — no versions left
   └─SDDP [f4570300] log:
     ├─possible versions are: 0.3.1 or uninstalled
     └─SDDP [f4570300] is fixed to version 0.3.1

I appreciate your help.

**Comment by odow** [comment] 2020-03-12 23:43
That's unusual. It should be fine on a clean install. Is this on JuliaPro? I would just use normal Julia. SDDP.jl isn't part of the JuliaPro distribution, so we have some compatibility issues.

Try
```Julia
import Pkg
Pkg.rm("SDDP")
Pkg.update()
Pkg.add("SDDP")
Pkg.add("JuMP")
```

**Comment by odow** [comment] 2020-03-12 23:44
Potentially duplicate of #309. Do you know @kavithagmenon?

I'll try installing Julia 1.0.5 and see what the problem is.

**Comment by marykh162** [comment] 2020-03-13 00:38
> That's unusual. It should be fine on a clean install. Is this on JuliaPro? I would just use normal Julia. SDDP.jl isn't part of the JuliaPro distribution, so we have some compatibility issues.
> 
> Try
> 
> ```julia
> import Pkg
> Pkg.rm("SDDP")
> Pkg.update()
> Pkg.add("SDDP")
> Pkg.add("JuMP")
> ```

Yes, this is on JuliaPro. Could that be because I have another version of JuliaPro on my computer? 
I tried what you suggested and I was able to add the SDDP package, but I don't know why version 0.1.0 is added not 0.3.0.

julia> Pkg.status()
    Status `C:\Users\user\.juliapro\JuliaPro_v1.0.5-2\environments\v1.0\Project.toml`
  [c52e3926] Atom v0.11.2
  [e2554f3b] Clp v0.7.1
  [60bf3e95] GLPK v0.12.1
  [7073ff75] IJulia v1.20.0
  [4076af6c] JuMP v0.20.1
  [e5e0dc1b] Juno v0.7.2
  [f4570300] MathOptFormat v0.4.0 #master (https://github.com/odow/MathOptFormat.jl.git)
  [f4570300] SDDP v0.1.0

Now, when I try to run a piece of code from SDDP.jl documentation, I am getting the following error:
ERROR: LoadError: type DataType has no field kwargs

**Comment by marykh162** [comment] 2020-03-13 00:39
> Potentially duplicate of #309. Do you know @kavithagmenon?
> 
> I'll try installing Julia 1.0.5 and see what the problem is.

No, I don't know this user.

**Comment by odow** [comment] 2020-03-13 00:41
Okay. It looks like SDDP.jl doesn't work on JuliaPro :(

JuliaPro curates a fixed set of packages that work well together. SDDP.jl isn't one of those packages. In our case, they bundle JuMP 0.20, instead of JuMP 0.21 so we're out of luck.

I would just install and use Julia 1.3 from here: https://julialang.org/downloads/.

**Comment by marykh162** [comment] 2020-03-13 00:44
> Okay. It looks like SDDP.jl doesn't work on JuliaPro :(
> 
> JuliaPro curates a fixed set of packages that work well together. SDDP.jl isn't one of those packages. In our case, they bundle JuMP 0.20, instead of JuMP 0.21 so we're out of luck.
> 
> I would just install and use Julia 1.3 from here: https://julialang.org/downloads/.

But I used to work with SDDP.jl on JuliaPro earlier. It is not working now that I installed the new version of JuliaPro.

**Comment by marykh162** [comment] 2020-03-13 01:08
> > Okay. It looks like SDDP.jl doesn't work on JuliaPro :(
> > JuliaPro curates a fixed set of packages that work well together. SDDP.jl isn't one of those packages. In our case, they bundle JuMP 0.20, instead of JuMP 0.21 so we're out of luck.
> > I would just install and use Julia 1.3 from here: https://julialang.org/downloads/.
> 
Unfortunately, I get errors on both Julia 1.0.5. and 1.3.
With Julia 1.0.5, I was able to add SDDP and JuMP, but when I run using SDDP, JuMP, I get the following error:

ERROR: Failed to precompile SDDP [f4570300-c277-11e8-125c-4912f86ce65d] to C:\Us
ers\user\.julia\compiled\v1.0\SDDP\rTTnU.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1203
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853

With Julia 1.3, I get the following error when I try to add the SDDP package:
ERROR: Unable to automatically install 'OpenSpecFun' from 'C:\Users\user\.julia\
packages\OpenSpecFun_jll\HMSwk\Artifacts.toml'

I would appreciate your help.

**Closed** 2020-03-22 17:57 UTC

**Comment by odow** [comment] 2020-03-22 17:58
Oops. I just saw this. Did you sort it out?

**Comment by marykh162** [comment] 2020-03-22 18:12
> 
> 
> Oops. I just saw this. Did you sort it out?

No problem. Yes, I had to install WMF 3.
