### ISSUE TITLE
Historical Simulation - BoundsError

### ISSUE THREAD

**Issue by FelipeNazare** [odow/SDDP.jl#440] opened 2021-07-04 19:50 UTC
Hi everyone,

I am trying to simulate using the SDDP.Historical scheme, however there is an "ERROR: LoadError: BoundsError".
Trying in a smaller example, similar issue occurred, as shown below.

Had anyone already faced this kind of issue?

Thanks for the help.

```
Solved in 0 iterations and 0.00 seconds
Optimal objective  1.750000000e+04

User-callback calls 291, time in user-callback 0.00 sec
ERROR: LoadError: BoundsError
Stacktrace:
 [1] getindex at .\number.jl:78 [inlined]
 [2] (::getfield(Main, Symbol("##580#584")){Int64,Array{VariableRef,1}})(::Float64) at .\REPL[886]:33
 [3] parameterize(::SDDP.Node{Int64}, ::Float64) at C:\Users\Felipe Nazaré\.julia\packages\SDDP\QO0wO\src\algorithm.jl:239
 [4] #solve_subproblem#57(::Bool, ::typeof(SDDP.solve_subproblem), ::SDDP.PolicyGraph{Int64}, ::SDDP.Node{Int64}, ::Dict{Symbol,Float64}, ::Float64, ::Array{Tuple{Int64,Float64},1}) at C:\Users\Felipe Nazaré\.julia\packages\SDDP\QO0wO\src\algorithm.jl:348
 [5] #solve_subproblem at .\none:0 [inlined]
 [6] #_simulate#68(::SDDP.Historical{Int64,Float64}, ::Dict{Symbol,Function}, ::Bool, ::Bool, ::Dict{Symbol,Float64}, ::typeof(SDDP._simulate), ::SDDP.PolicyGraph{Int64}, ::Array{Symbol,1}) at C:\Users\Felipe Nazaré\.julia\packages\SDDP\QO0wO\src\algorithm.jl:1025
 [7] #_simulate at .\none:0 [inlined]
 [8] #185 at C:\Users\Felipe Nazaré\.julia\packages\SDDP\QO0wO\src\plugins\parallel_schemes.jl:41 [inlined]
 [9] iterate at .\generator.jl:47 [inlined]
 [10] _collect(::UnitRange{Int64}, ::Base.Generator{UnitRange{Int64},getfield(SDDP, Symbol("##185#186")){Base.Iterators.Pairs{Symbol,Any,NTuple{5,Symbol},NamedTuple{(:sampling_scheme, :custom_recorders, :require_duals, :skip_undefined_variables, :incoming_state),Tuple{SDDP.Historical{Int64,Float64},Dict{Symbol,Function},Bool,Bool,Dict{Symbol,Float64}}}},SDDP.PolicyGraph{Int64},Array{Symbol,1}}}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at .\array.jl:619
 [11] collect_similar at .\array.jl:548 [inlined]
 [12] map at .\abstractarray.jl:2073 [inlined]
 [13] #_simulate#184 at C:\Users\Felipe Nazaré\.julia\packages\SDDP\QO0wO\src\plugins\parallel_schemes.jl:41 [inlined]
 [14] #_simulate at .\none:0 [inlined]
 [15] #simulate#71 at C:\Users\Felipe Nazaré\.julia\packages\SDDP\QO0wO\src\algorithm.jl:1166 [inlined]
 [16] (::getfield(SDDP, Symbol("#kw##simulate")))(::NamedTuple{(:sampling_scheme,),Tuple{SDDP.Historical{Int64,Float64}}}, ::typeof(SDDP.simulate), ::SDDP.PolicyGraph{Int64}, ::Int64, ::Array{Symbol,1}) at .\none:0 (repeats 3 times)
 [17] top-level scope at REPL[889]:1
in expression starting at REPL[889]:1
```

**Comment by odow** [comment] 2021-07-04 20:23
Please provide the code. 

Your historical sampling scheme needs to provide data that is passed to your `parameterize` function. It's likely that your parameterize function looks like
```Julia
Y = [1.0, 1.2, 1.4]
SDDP.parameterize(sp, 1:3) do w
    fix(y, Y[w])
end
```
and your `Historical` sampler passes in an index that violates the bounds of `Y`:
```Julia
simulations = SDDP.simulate(
    model,
    sampling_scheme = SDDP.Historical(
        [(1, 1), (2, 3), (3, 4)],
#                            ^ this is the bounds error because Y[4] doesn't exist
    ),
)
```

**Comment by odow** [comment] 2021-07-08 03:40
Closing since this is not a bug in SDDP.jl. If, after consulting your code and fixing the mistake you still have trouble, please re-open and provide a minimal working example.

**Closed by odow** 2021-07-08 03:40 UTC
Labels: question
