### ISSUE TITLE
Loading and writing cuts from files

### ISSUE THREAD

**Issue by adow031** [odow/SDDP.jl#467] opened 2021-09-03 03:28 UTC
I've encountered an issue with loading cuts from files.

It seems that in order to avoid cut selection on cuts loaded from a file these are not loaded into the bellman_function object, because cut_selection is set to `false` (they are directly loaded into the stage problems):

```julia
    # So the cuts are written to file after they have been normalized
    # to `θᴳ ≥ [θᵏ - ⟨πᵏ, xᵏ⟩] + ⟨πᵏ, x′⟩`. Thus, we pass `xᵏ=0` so that
    # eveything works out okay.
    # Importantly, don't run cut selection when adding these cuts.
    cuts = JSON.parsefile(filename, use_mmap = false)
    for node_cuts in cuts
        node_name = node_name_parser(T, node_cuts["node"])::T
        node = model[node_name]
        bf = node.bellman_function
        # Loop through and add the single-cuts.
        for json_cut in node_cuts["single_cuts"]
            coefficients = Dict{Symbol,Float64}(
                Symbol(k) => v for (k, v) in json_cut["coefficients"]
            )
            _add_cut(
                bf.global_theta,
                json_cut["intercept"],
                coefficients,
                Dict(key => 0.0 for key in keys(coefficients)),
                nothing,
                nothing;
                cut_selection = false,
            )
        end
```

However, this means if I save the cuts, these are empty, since the `write_cuts_to_file` function only looks in the `bellman_function` object when writing the cuts.

Have I done something wrong?

If not, I propose that either a user should be able to choose to allow cut selection on loaded cuts, or cuts loaded from a file should be stored in another object, which will be later written to a file.

Thanks.

**Comment by odow** [comment] 2021-09-03 04:04
Closing as a duplicate of https://github.com/odow/SDDP.jl/issues/360. I'll post in that issue with a follow-up comment.

**Closed by odow** 2021-09-03 04:04 UTC
