### ISSUE TITLE
Document how to access individual subproblems

### ISSUE THREAD

**Issue by BYS543** [odow/SDDP.jl#435] opened 2021-06-28 13:31 UTC
Hi, Oscar!
I want to print a model, however, i find print function doesn't work when I express this
```
ini_x=zeros(10);
index=[5,6]
model=SDDP.LinearPolicyGraph(
stages=10,
sense=:Min,
lower_bound=0.0,
optimizer=Gurobi.Optimizer,
integrality_handler=SDDP.SDDiP(),
)do sp1,stage
    @variable(sp1,0<=x[i in 1:10]<=1,SDDP.State,initial_value=ini_x[i])
    @constraint(sp1,[i in index],x[i].out>=0.5)
end
print(model[1].sp1)
```
it tells me 
`type PolicyGraph has no field sp1`
However when i write 
`print(model)` and `print(model[1])`, it can show some information ,but I still cannot see the constraints of subproblems in every stages.
Thank you!

**Comment by BYS-NCEPU** [comment] 2021-06-28 13:53
One more question, if I want to print a named constraint 
```
ini_x=zeros(10);
index=[5,6]
model=SDDP.LinearPolicyGraph(
stages=10,
sense=:Min,
lower_bound=0.0,
optimizer=Gurobi.Optimizer,
integrality_handler=SDDP.SDDiP(),
)do sp1,stage
    @variable(sp1,0<=x[i in 1:10]<=1,SDDP.State,initial_value=ini_x[i])
    @constraint(sp1,x_out[i in index],x[i].out>=0.5)
end
print(model[1].x_out)
```
can I use something like above?

**Comment by odow** [comment] 2021-06-28 19:00
```julia
print(model[1].subproblem)
```
and
```julia
print(model[1].subproblem[:x_out])
```

See `fieldnames(typeof(model[1])`.

Julia documentation: https://docs.julialang.org/en/v1/devdocs/reflection/#DataType-fields

**Comment by BYS-NCEPU** [comment] 2021-06-29 00:49
ok, thank you, Oscar, I just misunderstood the use of `model[1],subproblem`, it is the specified name `subproblem`, not the name user defined.

**Comment by odow** [comment] 2021-06-29 01:06
Correct. I'll leave this issue open as a reminder to better document this.

**Comment by BYS-NCEPU** [comment] 2021-06-29 08:24
Another problem of `print` function in SDDP
```
ini_x=zeros(10);
index=[5,6]
model=SDDP.LinearPolicyGraph(
stages=10,
sense=:Min,
lower_bound=0.0,
optimizer=Gurobi.Optimizer,
integrality_handler=SDDP.SDDiP(),
)do sp1,stage
    @variable(sp1,0<=x[i in 1:10]<=1,SDDP.State,initial_value=ini_x[i])
    @constraint(sp1,x_out[i in index],x[i].out>=0.5)
    @stageobjective(sp1,sum([x[i].out for i in 1:10]))
end
```
When I print the objective function, I find the stageobjective is 0, 
After using 
 `objective_function(model[1].subproblem)`,I still find the result is 0. why the stage objective is 0, i am a little confused about that.

**Comment by odow** [comment] 2021-06-30 21:12
It isn't set yet. You need to call `parameterize(node::Node, noise)` first (in your case `SDDP.parameterize(model[1], nothing)`). But this is undocumented and pretty internal. 

In general, you should not expect things in the subproblems to represent the actual model at a point in time, and there isn't support for people digging into the internal data structures.

What are you trying to achieve?

**Comment by BYS-NCEPU** [comment] 2021-07-01 00:56
well, I just want to check my objective whether it is right, now i know it may not be the problem of objective. Because my model is based on periods, and it is intractable, so i just consider to use SDDP, which it can decompose my model based on period, however, when i use `SDDP.ContinuousRelaxation`, it shows
```
User-callback calls 200, time in user-callback 0.00 sec
┌ Warning: Attempting to recover from serious numerical issues...
└ @ SDDP C:\Users\Lenovo\.julia\packages\SDDP\yCJkk\src\algorithm.jl:245
Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1288 rows, 843 columns and 3602 nonzeros
Model fingerprint: 0xba2a6fdb
Coefficient statistics:
  Matrix range     [1e-02, 2e+08]
  Objective range  [8e-01, 2e+02]
  Bounds range     [1e-05, 1e+03]
  RHS range        [9e-01, 1e+04]
Warning: Model contains large matrix coefficients
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.
Presolve removed 1009 rows and 757 columns
Presolve time: 0.01s

Solved in 0 iterations and 0.01 seconds
Infeasible model

User-callback calls 34, time in user-callback 0.00 sec
ERROR: LoadError: Unable to retrieve solution from 3.
  Termination status: INFEASIBLE
  Primal status:      NO_SOLUTION
  Dual status:        NO_SOLUTION.
A MathOptFormat file was written to `subproblem_3.mof.json`.
```
If I solve my model in the whole period, it can be solved although it may take a long time. 
For dynamic programming problems with strong coupling during process(e.g. some examples in graph theory,), does SDDP have good effect?

**Comment by odow** [comment] 2021-07-01 01:38
This type of time-staged linear problem can be decomposed and solved with SDDP.jl. 

But SDDP.jl doesn't implement Benders feasibility cuts, so your model must have relatively complete recourse. That means, the decision you take in one stage can't lead to an infeasibility in a future stage. The easiest way around this is to relax some of the constraints and add penalty terms to the objective for violating those constraints.

**Comment by BYS-NCEPU** [comment] 2021-07-01 02:12
Thank you for your prompt reply. I have tried to relax some of my constraints, which may be infeasible, however, iteration still stop with the infeasibility, 
```
User-callback calls 163, time in user-callback 0.00 sec
┌ Warning: Attempting to recover from serious numerical issues...
└ @ SDDP C:\Users\Lenovo\.julia\packages\SDDP\yCJkk\src\algorithm.jl:245
Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1288 rows, 843 columns and 3796 nonzeros
Model fingerprint: 0x9b6eb2d5
Coefficient statistics:
  Matrix range     [1e-02, 4e+07]
  Objective range  [8e-01, 2e+02]
  Bounds range     [3e-05, 1e+03]
  RHS range        [9e-01, 1e+06]
Presolve removed 1026 rows and 755 columns
Presolve time: 0.00s

Solved in 0 iterations and 0.00 seconds
Infeasible model

User-callback calls 29, time in user-callback 0.00 sec
ERROR: LoadError: Unable to retrieve solution from 2.
  Termination status: INFEASIBLE
  Primal status:      NO_SOLUTION
 ee https://odow.github.io/SDDP.jl/latest/tutorial/06_warnings/#Numerical-stability-1
for more information. Dual status:        NO_SOLUTION.
A MathOptFormat file was written to `subproblem_2.mof.json`.
See https://odow.github.io/SDDP.jl/latest/tutorial/06_warnings/#Numerical-stability-1
for more information.
```

**Comment by odow** [comment] 2021-07-01 02:22
> I have tried to relax some of my constraints, which may be infeasible, however, iteration still stop with the infeasibility,

Then the problem is infeasible due to some other constraints.

Also. Please use `set_silent(sp1)` in your model to turn off alll that printing...

**Comment by BYS-NCEPU** [comment] 2021-07-01 03:10
thank you, @odow, i will check the infeasible constraints carefully.

**Comment by BYS-NCEPU** [comment] 2021-07-01 10:09
@odow ,i feel it might not be the infeasibility(I've relaxed constraints that may lead to infeasibility),which interrupts the solving process,because it has completed one iteration, 
 Iteration    Simulation       Bound         Time (s)    Proc. ID   # Solves
        1    8.124707e+04   5.954530e+03   2.840002e-01          1         40
┌ Warning: Attempting to recover from serious numerical issues...
└ @ SDDP C:\Users\Lenovo\.julia\packages\SDDP\yCJkk\src\algorithm.jl:245
ERROR: LoadError: Unable to retrieve solution from 2.
  Termination status: INFEASIBLE
  Primal status:      NO_SOLUTION
  Dual status:        NO_SOLUTION.
A MathOptFormat file was written to `subproblem_2.mof.json`.
See https://odow.github.io/SDDP.jl/latest/tutorial/06_warnings/#Numerical-stability-1
for more information.
When the second iteration, the solving process terminates. And the prompt shows that the constraint is infeasible due to numerical problems.

**Comment by odow** [comment] 2021-07-01 20:36
The warning is misleading. Read this: https://github.com/odow/SDDP.jl/issues/436

**Comment by odow** [comment] 2021-08-15 02:06
Closing because I don't want to document this. 

Future readers: you're welcome to access the nodes via `model[1]` (if linear) or `model[(2, 3)]` (if Markovian) and access fields like `model[1].subproblem`, but this is undocumented and may break in any future release.

**Closed by odow** 2021-08-15 02:06 UTC
Labels: documentation
