### ISSUE TITLE
 SDDP.jl installation errors on Julia 1.0.5

### ISSUE THREAD

**Issue by kavithagmenon** [odow/SDDP.jl#309] opened 2020-03-12 02:40 UTC
Hi,
I tried to install SDDP.jl on Julia 1.0.5 and got the following errors. My understanding was that the latest version of SDDP.jl is compatible with  JuMP v0.19 and Julia v1.0 or higher versions. 

(v1.0) pkg>  add https://github.com/odow/SDDP.jl.git
  Updating registry at `C:\Users\kavit\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/odow/SDDP.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package JuMP [4076af6c]:
 JuMP [4076af6c] log:
 ├─possible versions are: [0.18.3-0.18.6, 0.19.0-0.19.2, 0.20.0-0.20.1, 0.21.0-0.21.1] or uninstalled
 ├─restricted to versions 0.21.0-0.21 by SDDP [f4570300], leaving only versions 0.21.0-0.21.1
 │ └─SDDP [f4570300] log:
 │   ├─possible versions are: 0.3.1 or uninstalled
 │   └─SDDP [f4570300] is fixed to version 0.3.1
 └─restricted to versions 0.20.1 by an explicit requirement — no versions left

These are the installed packages.
julia> Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 11 entries:
  "CSV"              => v"0.5.23"
  "GLPK"             => v"0.12.1"
  "Atom"             => v"0.11.3"
  "ZipFile"          => v"0.8.3"
  "SDDP"             => v"0.2.3"
  "CPLEX"            => v"0.6.3"
  "Juno"             => v"0.7.2"
  "JuMP"             => v"0.20.1"
  "MathProgBase"     => v"0.7.7"
  "Dates"            => nothing
  "MathOptInterface" => v"0.9.10"

  I tried to run one of the given examples (hydro thermal) and I always run into the error:
  
MethodError: no method matching Model(::Type{GLPK.Optimizer})
Closest candidates are:
  Model(::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any) at C:\Users\kavit\.julia\packages\JuMP\MsUSY\src\JuMP.jl:126
  Model(; caching_mode, solver) at C:\Users\kavit\.julia\packages\JuMP\MsUSY\src\JuMP.jl:163
  Model(!Matched::MathOptInterface.AbstractOptimizer, !Matched::Dict{MathOptInterface.ConstraintIndex,AbstractShape}, !Matched::Set{Any}, !Matched::Any, !Matched::Any, !Matched::Dict{Symbol,Any}, !Matched::Int64, !Matched::Dict{Symbol,Any}) at C:\Users\kavit\.julia\packages\JuMP\MsUSY\src\JuMP.jl:126
  ...
in top-level scope at base\none
in  at base\none
in #PolicyGraph#13 at SDDP\ERBpb\src\user_interface.jl:598
in construct_subproblem at SDDP\ERBpb\src\user_interface.jl:461

I would really appreciate any help!! Thanks in advance.

**Comment by odow** [comment] 2020-03-12 14:58
So it seems like you already have `SDDP` installed at version 0.2.3. Try running 
```Julia
import Pkg
Pkg.update()
```
To run the latest examples in the master branch, you need JuMP 0.21.

**Comment by kavithagmenon** [comment] 2020-03-12 16:53
Thanks @odow. I updated the packages and now I have
julia> Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 11 entries:
  "CSV"              => v"0.5.26"
  "GLPK"             => v"0.12.1"
  "Atom"             => v"0.12.9"
  "ZipFile"          => v"0.8.4"
  "SDDP"             => v"0.3.1"
  "CPLEX"            => v"0.6.3"
  "Juno"             => v"0.8.1"
  "JuMP"             => v"0.21.1"
  "MathProgBase"     => v"0.7.8"
  "Dates"            => nothing
  "MathOptInterface" => v"0.9.12"

I tried to solve the example _test_prob52_3stages_ and got the error:
MethodError: no method matching Model(::Type{GLPK.Optimizer})
Closest candidates are:
  Model(::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any) at C:\Users\kavit\.julia\packages\JuMP\MsUSY\src\JuMP.jl:126
  Model(; caching_mode, solver) at C:\Users\kavit\.julia\packages\JuMP\MsUSY\src\JuMP.jl:163
  Model(!Matched::MathOptInterface.AbstractOptimizer, !Matched::Dict{MathOptInterface.ConstraintIndex,AbstractShape}, !Matched::Set{Any}, !Matched::Any, !Matched::Any, !Matched::Dict{Symbol,Any}, !Matched::Int64, !Matched::Dict{Symbol,Any}) at C:\Users\kavit\.julia\packages\JuMP\MsUSY\src\JuMP.jl:126
  ...
in top-level scope at base\none
in test_prob52_3stages at untitled:4
in #LinearPolicyGraph at SDDP\ERBpb\src\user_interface.jl:488 
in  at base\none
in #PolicyGraph#13 at SDDP\ERBpb\src\user_interface.jl:598
in construct_subproblem at SDDP\ERBpb\src\user_interface.jl:461


Thanks.

**Comment by odow** [comment] 2020-03-12 16:57
You need to quit Julia and open a new session. You probably still have the old version of JuMP in memory.

**Comment by kavithagmenon** [comment] 2020-03-12 19:47
After opening a new session, for some reason none of my codes are running (its just stuck. No errors, no warnings, no results, nothing). I'm running julia in atom. Still trying to figure out whats happening there.

**Comment by odow** [comment] 2020-03-12 23:59
cc @marykh162

Hmm. I also had some issues installing SDDP.jl on Julia 1.0.5. Not really sure what the problem is. I think it's because I also have Julia 1.1 and 1.3 installed?

I use VSCode, rather than Atom so not much help there.

Here's the full log of things I had to do to get it working:

```Julia
Oscars-MBP:~ oscar$ exec '/Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.5 (2019-09-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  (empty environment)

(v1.0) pkg> add SDDP
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [f4570300] + SDDP v0.3.1
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [6e4b80f9] + BenchmarkTools v0.5.0
  [9e28174c] + BinDeps v1.0.0
  [b99e7846] + BinaryProvider v0.5.8
  [49dc2e85] + Calculus v0.5.1
  [523fee87] + CodecBzip2 v0.6.0
  [944b1d66] + CodecZlib v0.6.0
  [bbf7d656] + CommonSubexpressions v0.2.0
  [864edb3b] + DataStructures v0.17.10
  [163ba53b] + DiffResults v1.0.2
  [b552c78f] + DiffRules v1.0.1
  [f6369f11] + ForwardDiff v0.10.9
  [cd3eb016] + HTTP v0.8.12
  [83e8ac13] + IniFile v0.5.0
  [682c06a0] + JSON v0.21.0
  [7d188eb4] + JSONSchema v0.2.0
  [4076af6c] + JuMP v0.21.1
  [b8f27783] + MathOptInterface v0.9.12
  [739be429] + MbedTLS v0.6.8
  [d8a4904e] + MutableArithmetics v0.2.7
  [77ba4419] + NaNMath v0.3.3
  [bac558e1] + OrderedCollections v1.1.0
  [69de0a69] + Parsers v0.3.12
  [3cdcf5f2] + RecipesBase v0.7.0
  [189a3867] + Reexport v0.2.0
  [f4570300] + SDDP v0.3.1
  [276daf66] + SpecialFunctions v0.8.0
  [90137ffa] + StaticArrays v0.12.1
  [a759f4b9] + TimerOutputs v0.5.3
  [3bb67fe8] + TranscodingStreams v0.9.5
  [30578b45] + URIParser v0.4.0
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 

(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  [f4570300] SDDP v0.3.1

(v1.0) pkg> add JuMP
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [4076af6c] + JuMP v0.21.1
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]

(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  [4076af6c] JuMP v0.21.1
  [f4570300] SDDP v0.3.1

julia> using SDDP, JuMP
[ Info: Precompiling SDDP [f4570300-c277-11e8-125c-4912f86ce65d]
ERROR: LoadError: InitError: /Users/oscar/.julia/packages/SpecialFunctions/ne2iw/deps/usr/lib/libopenspecfun.1.3.dylib cannot be opened, Please re-run Pkg.build("SpecialFunctions"), and restart Julia.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] check_deps() at /Users/oscar/.julia/packages/SpecialFunctions/ne2iw/deps/deps.jl:20
 [3] __init__() at /Users/oscar/.julia/packages/SpecialFunctions/ne2iw/src/SpecialFunctions.jl:12
 [4] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:633
 [5] _require_from_serialized(::String) at ./loading.jl:684
 [6] _require(::Base.PkgId) at ./loading.jl:967
 [7] require(::Base.PkgId) at ./loading.jl:858
 [8] require(::Module, ::Symbol) at ./loading.jl:853
 [9] include at ./boot.jl:317 [inlined]
 [10] include_relative(::Module, ::String) at ./loading.jl:1044
 [11] include(::Module, ::String) at ./sysimg.jl:29
 [12] top-level scope at none:2
 [13] eval at ./boot.jl:319 [inlined]
 [14] eval(::Expr) at ./client.jl:393
 [15] top-level scope at ./none:3
during initialization of module SpecialFunctions
in expression starting at /Users/oscar/.julia/packages/ForwardDiff/vt5F1/src/ForwardDiff.jl:9
ERROR: LoadError: Failed to precompile ForwardDiff [f6369f11-7733-5829-9624-2563aa707210] to /Users/oscar/.julia/compiled/v1.0/ForwardDiff/k0ETY.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1203
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1044
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:393
 [12] top-level scope at ./none:3
in expression starting at /Users/oscar/.julia/packages/JuMP/CZ8vV/src/JuMP.jl:25
ERROR: LoadError: Failed to precompile JuMP [4076af6c-e467-56ae-b986-b466b2749572] to /Users/oscar/.julia/compiled/v1.0/JuMP/DmXqY.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1203
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1044
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:393
 [12] top-level scope at ./none:3
in expression starting at /Users/oscar/.julia/packages/SDDP/E7RLj/src/SDDP.jl:9
ERROR: Failed to precompile SDDP [f4570300-c277-11e8-125c-4912f86ce65d] to /Users/oscar/.julia/compiled/v1.0/SDDP/rTTnU.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1203
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853

(v1.0) pkg> build SpecialFunctions
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/ne2iw/deps/build.log`

(v1.0) pkg> build JuMP
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/ne2iw/deps/build.log`
  Building CodecZlib ───────→ `~/.julia/packages/CodecZlib/5t9zO/deps/build.log`
  Building MbedTLS ─────────→ `~/.julia/packages/MbedTLS/X4xar/deps/build.log`
  Building CodecBzip2 ──────→ `~/.julia/packages/CodecBzip2/T5yr7/deps/build.log`

julia> using JuMP
[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]

julia> using SDDP
[ Info: Precompiling SDDP [f4570300-c277-11e8-125c-4912f86ce65d]

```

**Comment by kavithagmenon** [comment] 2020-03-13 01:10
Thanks @odow  for your response. I guess in my case there is an issue with Atom or the julia-client package.  After the crash, I quit julia and started it again and I got the following error. _using JuMP_ or _using SDDP_ does not give me an error anymore.

Starting Julia...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.5 (2019-09-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> ┌ Warning: Atom.jl: unrecognised message `cacheCompletions`.
│ Please make sure your Atom and Julia packages are in sync.
│   - Try `using Pkg; Pkg.update()` to update this package.
│   - Check for `julia-client` updates in Atom.
└ @ Atom C:\Users\kavit\.julia\packages\Atom\cYxbS\src\comm.jl:175
julia> 

julia> using JuMP

julia> using SDDP

I have posted in the discussion board to see if anyone using Atom has experienced any similar issue. This is the first time Atom is giving me a warning 'cacheCompletions'.

Thanks.

**Comment by odow** [comment] 2020-03-22 19:51
Closing this because it seems resolved, or at the very least, is an issue with Atom and not SDDP.jl. 

Please re-open if that isn't the case.

**Closed** 2020-03-22 19:51 UTC
