### ISSUE TITLE
FileFormats not defined

### ISSUE THREAD

**Issue by bonnkleiford** [odow/SDDP.jl#515] opened 2022-03-09 09:50 UTC
Hi, Oscars!

I am currently solving a problem with SDDP.jl (actually a replication of your Dairy Farm Model), and I came across this error when I try to train the model:

![Screenshot 2022-03-09 at 10 47 07](https://user-images.githubusercontent.com/37835698/157416422-0b618a50-8e2b-42f6-91ce-e233c7f4b5ed.png)

I am not so sure how to go about it.

**Comment by odow** [comment] 2022-03-09 19:14
What is `import Pkg; Pkg.status()`? It looks like you've installed an old version somehow.

**Comment by bonnkleiford** [comment] 2022-03-10 12:49
Hi, Oscar!

Thanks for getting back to me quickly. Here it is:
<img width="390" alt="Screenshot 2022-03-10 at 13 48 50" src="https://user-images.githubusercontent.com/37835698/157665057-06a79340-6345-4be3-a807-3ca7c31c294b.png">

**Comment by odow** [comment] 2022-03-10 20:20
Okay, you're running some pretty old versions there!

Do
```Julia
import Pkg
Pkg.rm("MathOptFormat")
Pkg.update()
```

The latest version of SDDP.jl is v0.4.4. I think the problem is that you have MathOptFormat installed as an explicit dependency, which prevented things from updating. We moved MathOptFormat into JuMP, so now you can use JuMP to read/write files without relying on MathOptFormat.

**Comment by odow** [comment] 2022-03-10 20:20
Also, please update to Julia 1.6. We're dropping support for Julia 1.5, but the good news is that Julia 1.6 is the new long-term support release of Julia, so you'll be able to stay on it for a few years without having to change.

**Comment by odow** [comment] 2022-03-15 03:42
The error in the example you sent me is because you had 
```Julia
@variable(sp, 0 <= W, SDDP.State, initial_value = parameters["initial_soil_moisture"], ub = maximum_soil_moisture)
```
instead of
```Julia
@variable(sp, 0 <= W <= maximum_soil_moisture, SDDP.State, initial_value = parameters["initial_soil_moisture"])
```
We should check for unsupported keyword arguments here:
https://github.com/odow/SDDP.jl/blob/254f74d185e96c999b33dbeaf624e330f875adde/src/JuMP.jl#L50

I'll write you and email with some other suggestions.

**Comment by odow** [comment] 2022-10-14 02:18
Closing because this isn't a bug in SDDP.jl.

**Closed by odow** 2022-10-14 02:18 UTC
